# NumPy Functions :

In [17]:
import numpy as np

# arange()

In [18]:
#np.arange(START, END, STEP)
ar_1d = np.arange(1, 25, 2)
print(ar_1d)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [19]:
even_ar = np.arange(1, 13, 2)
even_ar

array([ 1,  3,  5,  7,  9, 11])

# linspace()

In [20]:
## we use linspace function when neeed values with equal gap
#np.linspace(start, end, how many values we need in start-end range)
np.linspace(1, 10, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# reshape()

In [21]:
## when we need to convert 1D arary into 2-3D array

In [22]:
ar_2d = ar_1d.reshape(3,4)
ar_2d

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [27]:
## conversion of 1D to 3D
##array name.reshape(3D,Rows,Column)
ar_3d = ar_1d.reshape(2,3,2)
ar_3d

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]])

In [32]:
ar=np.arange(1,13).reshape(4,3)
print(ar)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Ravel()

In [ ]:
#Ravel Function convert Multi-D to 1D

In [33]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Flatten()

In [34]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
#‘C’ means to flatten in row-major (C-style) order. 
ar.flatten(order= 'C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
# ‘F’ means to flatten in column-major (Fortran- style) order. 
ar.flatten(order='F')

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [37]:
# ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. 
ar.flatten(order='A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
# ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.
ar.flatten(order='K')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose()

In [39]:
# convert Row into Column

In [41]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
ar.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [42]:
## short key for transpose
ar.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# Concatenate & Sort( )

In [8]:
import numpy as np

In [9]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [10]:
b=np.array([20,30,40,50,60,70,80])

In [13]:
c= np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 30, 40,
       50, 60, 70, 80])

In [15]:
c.sort()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 30, 40,
       50, 60, 70, 80])

# 2-D Arrays

In [31]:
d2 = np.array([[5,67,20],
            [10,20,30],
            [30,40,50]])
d2

array([[ 5, 67, 20],
       [10, 20, 30],
       [30, 40, 50]])

In [32]:
d2.ndim

2

In [37]:
d3=np.array([[[1,2,3],[1,2,3],[1,2,3]],
            [[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
d3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [38]:
d3.ndim

3

In [39]:
d3.size

27

In [40]:
d3.shape

(3, 3, 3)

In [42]:
d3.sort()
d3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [48]:
new=np.arange(9)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
new.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
np.reshape(new, newshape=(1,9),order="F")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Reshape with New Axis

In [57]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Row Wise 
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
# Column Wise 
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [60]:
a[2:5]

array([3, 4, 5])