# NUMPY 

In [2]:
import numpy as np

### Create an arry hich contain first 19 digit


In [5]:
arr=np.arange(20)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [8]:
type(arr_1d)

numpy.ndarray

In [9]:
arr_1d.ndim

1

In [13]:
arr_2d=np.array([[1,2,3,4], [5,6,7,8,]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


### Array Dimension type  

In [14]:
arr_2d.ndim

2

### Array Size 

In [16]:
arr_1d.size

4

In [17]:
arr_2d.size

8

### Array Shape which tells us Rows & Columns

### we 2 rows & 4 Columns

In [20]:
arr_2d.shape


(2, 4)

### dtype(int 32) tells us about data type which is int and saved in 32 bits

In [19]:
arr_2d.dtype

dtype('int32')

In [21]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr_3d=np.array([[1,1,1], [1,1,1],[1,0,1]])
arr_3d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 1]])

In [35]:
mx_1s =np.ones(5)
mx_1s

array([1., 1., 1., 1., 1.])

In [32]:
mx_1s.dtype

dtype('float64')

In [36]:
mx_2s = np.ones((3,4))
print(mx_2s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
mx_1s = np.ones((3,4), dtype = int )
mx_1s

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
mx_0s=np.zeros((4,6),)
mx_0s

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
mx_0s = np.zeros((4,6), dtype= bool)
mx_0s

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [44]:
mx_0s = np.zeros((4,6), dtype= str)
mx_0s

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [45]:
mx_0s = np.empty((3,3))
mx_0s

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.79044937e-321],
       [6.23041391e-307, 1.60219034e-306, 1.89145199e-307]])