# Python Numpy Array Slicing

In [1]:
import numpy as np

In [2]:
mx = np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [3]:
## Access specific value from matrix using index 
mx[0,0]

1

In [4]:
## Dimension type
mx[0,0].ndim

0

In [5]:
## Print specific row or column
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [7]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [8]:
mx[:,0:1].ndim

2

In [9]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [10]:
mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [11]:
mx[1:4,1:4].ndim

2

In [13]:
mx[:,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [14]:
## size in byte
mx.itemsize

4

In [15]:
mx.dtype

dtype('int32')

# Python Numpy Conctination and Split

In [16]:
import numpy as np 

In [19]:
m_1 = np.arange(1,17).reshape(4,4)
m_2 = np.arange(17,33).reshape(4,4)

In [22]:
print(m_1, m_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [24]:
## conctination of list VS Array
list1=[2,4,5,6]
list2=[7,8,9,10]
list1 + list2

[2, 4, 5, 6, 7, 8, 9, 10]

In [25]:
## See the Diffirence
m_1 + m_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [32]:
np.concatenate((m_1, m_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [33]:
## Column vise Concat
np.concatenate((m_1,m_2), axis= 1 )

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [35]:
## Row vise Concat or virtival concatenate
np.vstack((m_1,m_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [37]:
np.hstack((m_1,m_2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [40]:
## Multiple array concatenation  
np.hstack((m_1,m_2,m_1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

# Split Array

In [50]:
np.split(m_1,2)
#see Difference

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [51]:
## Original Array
m_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
list1 = np.split(m_1,2)
type(list1)

list

In [53]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
type(list1[0])

numpy.ndarray

In [57]:
m_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
## Column Vise Split
np.split(m_1, 2, axis= 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [58]:
d1 = np.array([1,2,2,4,4]) 

In [59]:
## [1,3] DESCRIBE ABOUT PICK VALUE FOR ARRAY 1 BEFORE 1ST INDEX & AFTER THAT PICK VALUE BEFORE 3 INDEX 
np.split(d1,[1,3])


[array([1]), array([2, 2]), array([4, 4])]

In [24]:
import numpy as np

In [25]:
a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
a=a.reshape(10,10)

In [9]:
a.ndim

2

In [10]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [13]:
# b=np.array(a[1:4,1:4])
# b

In [17]:
b=a[1:4,1:4]
b

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [18]:
c=b*5
c

array([[ 60,  65,  70],
       [110, 115, 120],
       [160, 165, 170]])

In [23]:
a

array([[ 575,  600],
       [ 825, 4250]])

In [27]:
a[1:4,1:4]=a[1:4,1:4]*5
a


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  60,  65,  70,  15,  16,  17,  18,  19,  20],
       [ 21, 110, 115, 120,  25,  26,  27,  28,  29,  30],
       [ 31, 160, 165, 170,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
a[1:4,1:4]=0
b=a.mean()
b

48.43

In [33]:
a[1:4,1:4]=b
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  48,  48,  48,  15,  16,  17,  18,  19,  20],
       [ 21,  48,  48,  48,  25,  26,  27,  28,  29,  30],
       [ 31,  48,  48,  48,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [34]:
a.max()

100

In [35]:
a.min()

1

In [1]:
a.put

NameError: name 'a' is not defined